### ISSUE TITLE
your extension created two bak files and hard coded two core files?

### ISSUE THREAD

**Issue by MixingOnBeat** [ForumHulp/helper#1]
Testing phpBB 3.1.9

Yesterday I tried installing your extension: **Pages: TinyMCE WYSIWYG Add-on 3.1.1** -- when trying to install that, it alerted me that I had to install another extension in order to make it work. So I installed: **Forumhulp Helper 3.1.7** 

Both installations went well, and I tested the first extension for the pages extension and didn't spot an error.

Today I did a backup of my files, and noticed that it seems it had edited and created two .bak files of core phpbb files.  I'd like to confirm if it was actually your extensions that did that?  Because I did not make any other installations for a week and I do weekly backups of my files.

The two files in question and their paths are:

```
/adm/style/acp_ext_list.html.bak
/includes/acp/acp_extensions.php.bak
```

I did compare the baks against the ones it edited, and did notice the file changes within.  Plus also compared them to my last weekly backup and noticed they were changed.

Another issue is that the files it edited (not the baks), it CHMOD them to 600 instead of 644 -- don't know if that is normal.  I am positive that the original files were CHMOD to 644.

NOTE: this site is not live, I have it in a private server--just for testing beta extensions and etc.

So please let me know?  Is your extension designed to hardcode those two files and also create baks for them?

I tried contacting you via phpbb, but noticed that the extension was locked in the forum: https://www.phpbb.com/community/viewtopic.php?f=456&t=2267456 -- so I decided to contact you via github instead.

**Comment by ForumHulp** [comment]
Yes it made the changes.

Greetz

Van: MOB [mailto:notifications@github.com] 
Verzonden: zaterdag 4 juni 2016 19:29
Aan: ForumHulp/helper helper@noreply.github.com
Onderwerp: [ForumHulp/helper] your extension created two bak files and hard coded two core files? (#1)

Testing phpBB 3.1.9

Yesterday I tried installing your extension: Pages: TinyMCE WYSIWYG Add-on 3.1.1 -- when trying to install that, it alerted me that I had to install another extension in order to make it work. So I installed: Forumhulp Helper 3.1.7 

Both installations went well, and I tested the first extension for the pages extension and didn't spot an error.

Today I did a backup of my files, and noticed that it seems it had edited and created two .bak files of core phpbb files. I'd like to confirm if it was actually your extensions that did that? Because I did not make any other installations for a week and I do weekly backups of my files.

The two files in question and their paths are:
/adm/style/acp_ext_list.html.bak
/includes/acp/acp_extensions.php.bak

I did compare the baks against the ones it edited, and did notice the file changes within. Plus also compared them to my last weekly backup and noticed they were changed.

Another issue is that the files it edited (not the baks), it CHMOD them to 600 instead of 644 -- don't know if that is normal. I am positive that the original files were CHMOD to 644.

NOTE: this site is not live, I have it in a private server--just for testing beta extensions and etc.

So please let me know? Is your extension designed to hardcode those two files and also create baks for them?

I tried contacting you via phpbb, but noticed that the extension was locked in the forum: https://www.phpbb.com/community/viewtopic.php?f=456 https://www.phpbb.com/community/viewtopic.php?f=456&t=2267456 &t=2267456 -- so I decided to contact you via github instead.

**Comment by MixingOnBeat** [comment]
Can CHMOD those two files to 600 be an issue?  i wonder?

**Comment by ForumHulp** [comment]
Don’t think so as php wrote it and it also can read it.

Are you able to see extension manager?

Let’s hope the needed event is in phpbb soon.

Greetz

Van: MOB [mailto:notifications@github.com] 
Verzonden: zaterdag 4 juni 2016 22:30
Aan: ForumHulp/helper helper@noreply.github.com
CC: Forumhulp.com info@forumhulp.com; Comment comment@noreply.github.com
Onderwerp: Re: [ForumHulp/helper] your extension created two bak files and hard coded two core files? (#1)

Can CHMOD those two files to 600 be an issue? i wonder?

**Comment by MixingOnBeat** [comment]
> Are you able to see extension manager?

Yes I could.  I have no clue why those two replaced files were CHMOD to 600 plus still be viewable in the ACP.

Have you already requested phpBB to create those two EVENTS?

**Comment by MixingOnBeat** [comment]
Hello again,

I was wondering?  What happens when we disable or uninstall the extension?  Does it replace the bak files?  

I've been studying the part of the command, but don't see how it suppose to replace the two files? https://github.com/ForumHulp/helper/blob/master/migrations/v31x/m1_initial_file.php#L66

What I did was reverted the changes on the files by using my last backup.  And then I uninstalled the extension.  I did not see that it tried to replace the files.  Furthermore, I then tried to reinstall the extension, but this time it did not create the edits nor the bak files. 

So is it a one time deal?

**Comment by Galixte** [comment]
Hi @ForumHulp @MixingOnBeat,

Any news about this ?

**Comment by ForumHulp** [comment]
Oooh sorry I didn't read the message 
Yes when deinstalled it will check if other forumhulp extensions are still enabled and if not it will revert the changed files. The bak file will stay unchanged.

**Comment by Galixte** [comment]
Thanks !
